source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
inhibit_all_warnings!

xcodeproj 'LGRefreshViewDemo'

target 'LGRefreshViewDemo' do
    pod 'LGRefreshView', :path => '../'
    pod 'LGHelper', '~> 1.0.0'
end
